feat: add optional mailpit configuration
frappe/frappe_docker pull request #1269
Opened 2023-11-09 08:24 UTC by WebsiteDeveloper

> Please provide enough information so that others can review your pull request:

> Explain the **details** for making this change. What existing problem does the pull request solve?

2023-11-09 21:45 UTC, revant requested changes

2023-11-09 21:45 UTC, revant commented on devcontainer-example/docker-compose.yml
> +  #    restart: always
Don't set restart: always. Other services don't set it.

2023-11-09 22:33 UTC, revant commented
Greenmail allows SMTP as well as IMAP locally:

```yaml
  greenmail:
    image: greenmail/standalone:2.0.0
    ports:
      - 3025:3025
      - 3110:3110
      - 3143:3143
      - 3465:3465
      - 3993:3993
      - 8181:8080
```

2023-11-13 06:55 UTC, revant commented
Either allow edit or remove the restart and container_name.

2023-11-13 10:29 UTC, WebsiteDeveloper commented
@revant sorry for the delayed response i removed the container name and restart.

Concerning greenmail, the main reason why we use mailpit is because it has a webinterface which greenmail does not to my knowledge

2023-11-13 21:40 UTC, revant approved these changes

2023-11-13 21:40 UTC, merged

2023-11-14 05:02 UTC, revant commented
> Concerning greenmail, the main reason why we use mailpit is because it has a webinterface which greenmail does not to my knowledge

It gives http rest api. You'll need to configure thunderbird or some mail client with `localhost:3025` for SMTP and `localhost:3143` for IMAP